[package]
name = "Caevern"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "30.0.0"
cgmath = "0.18"
winit = "0.30.13"
env_logger = "0.11.11"
pollster = "1.0.1"
openxr = "0.21.1"
rust-embed = "8.12.0"
image = "0.25.10"
bytemuck = { version = "1.25.2", features = ["derive"] }
fbx = "0.2"
fontdue = "0.9.4"
tokio-tungstenite = "0.30.0"
futures-util = "0.3.34"
url = "2.5.8"
tokio = "1.53.1"
tungstenite = { version = "0.30.0", features = ["native-tls"] }
cap = "0.1.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
webrtc = "0.20.3"
async-trait = "0.1.92"
rtc = "0.20.3"
rand = "0.10.2"
cpal = "0.18.2"
opus = "0.3.1"
